# Basic configuration
title: Daniel Donnelly
baseurl: "" # Leave blank
url: "https://danieldonnelly7.github.io"

# Use a simpler theme
theme: jekyll-theme-minimal

# Author information
author:
  location: "United Kingdom"
  avatar: "./profile.jpg" # File path for the image
  email: "danieldonnelly46@gmail.com"

# Navigation
nav:
  - title: "About"
    url: /
