# Basic configuration
title: Daniel Donnelly
description: AI Researcher
baseurl: "" # Leave blank
url: "https://danieldonnelly7.github.io"

# Theme and plugins
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Author information
author:
  name: "Daniel Donnelly"
  avatar: "/assets/images/profile.jpg"
  bio: "I’m an AI researcher with experience in machine learning, reinforcement learning, uncertainty quantification, and runtime verification. My current research focuses on developing language-based approaches for reward specification and monitoring for reinforcement learning agents, leveraging frameworks like Runtime Monitoring Language (RML)."
  location: "United Kingdom"
  email: "danieldonnelly46@gmail.com"

# Social media icons
social:
  email: danieldonnelly46@gmail.com
  github: danieldonnelly7
  linkedin: daniel-donnelly-428701170
