# Basic configuration
title: Daniel Donnelly
description: AI Researcher
baseurl: "" # Leave blank
url: "https://danieldonnelly7.github.io"

# Use a simpler theme
theme: jekyll-theme-primer

# Author information
author:
  name: "Daniel Donnelly"
  bio: "I’m an AI researcher with experience in machine learning, reinforcement learning, uncertainty quantification, and runtime verification."
  location: "United Kingdom"
  email: "danieldonnelly46@gmail.com"

# Navigation
nav:
  - title: "About"
    url: /
